RestApiWebApplication/Controllers/InicioController.cs
using Microsoft.AspNetCore.Mvc;

using RestApiWebApplication.Models;
using RestApiWebApplication.Resources;
using RestApiWebApplication.Services;

using System.Security.Claims;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authentication;

namespace RestApiWebApplication.Controllers
{
    public class InicioController : Controller
    {
        private readonly IUsuarioService _usuarioServicio;
        public InicioController(IUsuarioService usuarioServicio)
        {
            _usuarioServicio = usuarioServicio;
        }

        public IActionResult Registrarse()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Registrarse(Usuario modelo)
        {
            modelo.Password = Utilidades.EncriptarClave(modelo.Password);

             Usuario usuarioExistente = await _usuarioServicio.GetUsuario(modelo.Correo, modelo.Password);

            if (usuarioExistente != null)
            {
                ViewData["Mensaje"] = "Ya existe un usuario con este correo electrónico";
                return View();
            }

            Usuario usuario_creado = await _usuarioServicio.SaveUsuario(modelo);

            if (usuario_creado.IdUsuario > 0){
                // return RedirectToAction("IniciarSesion", "Inicio");
                List<Claim> claims = new List<Claim>() {
                    new Claim(ClaimTypes.Name, usuario_creado.NombreUsuario),
                    new Claim("Apellido",usuario_creado.ApellidoUsuario),
                    new Claim("Correo", usuario_creado.Correo),
                    new Claim("Password", usuario_creado.Password),
                    new Claim("Ubicacion", usuario_creado.Ubicacion)
                };

                ClaimsIdentity claimsIdentity = new ClaimsIdentity(claims, CookieAuthenticationDefaults.AuthenticationScheme);
                AuthenticationProperties properties = new AuthenticationProperties()
                {
                    AllowRefresh= true
                };

                await HttpContext.SignInAsync(
                    CookieAuthenticationDefaults.AuthenticationScheme,
                    new ClaimsPrincipal(claimsIdentity),
                    properties
                    );

                return RedirectToAction("Index", "System");
            }else{
                ViewData["Mensaje"] = "No se pudo crear el usuario";
                return View();
            }
        }

        public IActionResult IniciarSesion()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> IniciarSesion(string correo, string password)
        {

            Usuario usuario_encontrado = await _usuarioServicio.GetUsuario(correo, Utilidades.EncriptarClave(password));

            if (usuario_encontrado == null) {
                ViewData["Mensaje"] = "No se encontraron coincidencias";
                return View();
            }

            List<Claim> claims = new List<Claim>() {
                new Claim(ClaimTypes.Name, usuario_encontrado.NombreUsuario),
                new Claim("Apellido",usuario_encontrado.ApellidoUsuario),
                new Claim("Correo", usuario_encontrado.Correo),
                new Claim("Password", usuario_encontrado.Password),
                new Claim("Ubicacion", usuario_encontrado.Ubicacion)
            };

            ClaimsIdentity claimsIdentity = new ClaimsIdentity(claims, CookieAuthenticationDefaults.AuthenticationScheme);
            AuthenticationProperties properties = new AuthenticationProperties()
            {
                AllowRefresh= true
            };

            await HttpContext.SignInAsync(
                CookieAuthenticationDefaults.AuthenticationScheme,
                new ClaimsPrincipal(claimsIdentity),
                properties
                );

            return RedirectToAction("Index", "System");
        }
    }
}

RestApiWebApplication/Views/Inicio/IniciarSesion.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>IniciarSesion</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
</head>
<body>

    <div class="container mt-5 pt-5">

        <div class="row justify-content-center">
            <div class="col-12 col-xl-4 col-md-6">

                <div class="card">
                    <div class="card-header">
                        Inicio Sesion
                    </div>
                    <div class="card-body">

                        <form asp-controller="Inicio" asp-action="IniciarSesion" method="post">

                            <input class="form-control mb-3" type="text" placeholder="Correo" required name="correo" />
                            <input class="form-control mb-3" type="password" placeholder="Contraseña" required name="password" />
                            <div class="d-grid gap-2 mb-3">
                                <button class="btn btn-primary" type="submit">Iniciar Sesion</button>
                            </div>
                            @if (ViewData["Mensaje"] != null)
                            {
                                
                                <div class="form-group">
                                    <div class="alert alert-danger" role="alert">
                                        @ViewData["Mensaje"]
                                    </div>
                                </div>
                            }
                            ¿No tienes una cuenta? <a href="@Url.Action("Registrarse","Inicio")"> Registrate aquí</a>

                        </form>

                    </div>

                </div>

            </div>
        </div>

    </div>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>

RestApiWebApplication/Views/Inicio/Registrarse.cshtml
@model RestApiWebApplication.Models.Usuario;
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Registro</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
</head>
<body>


    <div class="container mt-5 pt-5">

        <div class="row justify-content-center">
            <div class="col-12 col-xl-4 col-md-6">

                <div class="card">
                    <div class="card-header">
                       <h1>Registrate</h1>
                    </div>
                    <div class="card-body">

                        <form asp-controller="Inicio" asp-action="Registrarse" method="post">

                            <input class="form-control mb-3" type="text" placeholder="Nombre(s)" asp-for="NombreUsuario" required />
                            <input class="form-control mb-3" type="text" placeholder="Apellidos" asp-for="ApellidoUsuario" required />
                            <input class="form-control mb-3" type="text" placeholder="Correo" required asp-for="Correo" />
                            <input class="form-control mb-3" type="password" placeholder="Contraseña" required asp-for="Password" />
                            <input class="form-control mb-3" type="text" placeholder="Ubicación" asp-for="Ubicacion" required />
                            <div class="d-grid gap-2 mb-3">
                                <button class="btn btn-primary" type="submit">Registrate</button>
                            </div>
                            @if (ViewData["Mensaje"] != null)
                            {

                                <div class="form-group">
                                    <div class="alert alert-danger" role="alert">
                                        @ViewData["Mensaje"]
                                    </div>
                                </div>
                            }
                            ¿Ya tienes una cuenta? <a href="@Url.Action("IniciarSesion","Inicio")"> Iniciar Sesion</a>

                        </form>

                    </div>

                </div>

            </div>
        </div>

    </div>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>